#!/command/with-contenv bash

echo "**** Adding python and pip as repo dependencies ****"
echo "python3" >> /mod-repo-packages-to-install.list
echo "py3-pip" >> /mod-repo-packages-to-install.list

echo "**** Adding requests-unixsocket as pip dependency ****"
echo "requests-unixsocket" >> /mod-pip-packages-to-install.list
