#!/usr/bin/with-contenv bash

echo "**** Installing python and pip ****"
apk --update --no-cache add \
    python3 \
    py3-pip 

echo "**** Installing required python modules ****"
pip3 install requests-unixsocket

exit 0
